### ISSUE TITLE
ninja -C out/Default all

### ISSUE THREAD

**Issue by geekchenwu** [rpavlik/fluoride#1]
just run：ninja -C out/Default all
some error like this：
ninja: error: '../../common/timer.cc', needed by 'obj/common/libcommon.timer.o', missing and no known rule to make it

**Comment by jaybajing** [comment]
Dear Sir,

I also facing the same issue now.
how to fixed it? @rpavlik

**Comment by rpavlik** [comment]
Sorry, no idea. This was just an experiment years ago.
